//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Metroit.RakurakuKintai.Api.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ApiUriResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApiUriResources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Metroit.RakurakuKintai.Api.Properties.ApiUriResources", typeof(ApiUriResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   /{0}/api/ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ApiRelativeUriPath {
            get {
                return ResourceManager.GetString("ApiRelativeUriPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   /attendance-time-requests に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AttendanceTimeRequests {
            get {
                return ResourceManager.GetString("AttendanceTimeRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   https://rkkungfu.rakurakukintai.jp/ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BaseUri {
            get {
                return ResourceManager.GetString("BaseUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   /daily-workings/{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DailyWorkings {
            get {
                return ResourceManager.GetString("DailyWorkings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   /date-times に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DateTimes {
            get {
                return ResourceManager.GetString("DateTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   /employees/me に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EmployeesMe {
            get {
                return ResourceManager.GetString("EmployeesMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   /employees/me/affiliation-and-availability に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EmployeesMeAffiliationAndAvailability {
            get {
                return ResourceManager.GetString("EmployeesMeAffiliationAndAvailability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   /leave-requests に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LeaveRequests {
            get {
                return ResourceManager.GetString("LeaveRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   /leaves/{0}/available に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LeavesAvailable {
            get {
                return ResourceManager.GetString("LeavesAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   /login に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   /logout に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   /daily-workings/me/{0:yyyy-MM-dd}/memo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Memo {
            get {
                return ResourceManager.GetString("Memo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   /overtime-requests に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OvertimeRequests {
            get {
                return ResourceManager.GetString("OvertimeRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   /daily-workings/{0}/{1:yyyy-MM-dd} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RegisteredStatusOfDay {
            get {
                return ResourceManager.GetString("RegisteredStatusOfDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   /time-records に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TimeRecords {
            get {
                return ResourceManager.GetString("TimeRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   /working-patterns/{0}/available に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WorkingPatterns {
            get {
                return ResourceManager.GetString("WorkingPatterns", resourceCulture);
            }
        }
    }
}
